[package]
name = "bpf-program-template"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "=1.7.12"
thiserror = "1.0.29"



[dev-dependencies]

solana-program-test = "=1.7.12"


[lib]
crate-type = ["cdylib", "lib"]
